# config.yaml
dataset: # used for prepare_dataset.py
  path: "data/raw/dataset"
  json_path: "data/processed/data.json"
  samples_to_consider: 661500  # 22050 * 30, 1 sec worth of loading audio with librosa is 22050 samples/sec, multiply by 30 for 30 seconds, standardizes length of the audio files
  n_mfcc: 13
  n_fft: 2048
  hop_length: 512

training: # used to train_model.py
  data_path: "data/processed/data.json"
  learning_rate: 0.0001
  epochs: 40
  batch_size: 32
  patience: 5
  saved_model_path: "models/model.h5"
  test_size: 0.2
  validation_size: 0.2
